# Generated by Django 5.2.3 on 2026-03-26 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bantuan", "0001_initial"),
        ("masyarakat", "0003_wilayah"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pengajuan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("diproses", "Diproses"),
                            ("ditolak", "Ditolak"),
                            ("diterima", "Diterima"),
                            ("revisi", "Perlu Revisi"),
                        ],
                        default="Diproses",
                        max_length=100,
                    ),
                ),
                (
                    "file_pengajuan",
                    models.FileField(blank=True, null=True, upload_to="pengajuan/"),
                ),
                ("tanggal_verifikasi", models.DateField(blank=True, null=True)),
                ("catatan", models.TextField(blank=True, null=True)),
                ("tanggal_pengajuan", models.DateField(auto_now_add=True)),
                ("tanggal_diperbarui", models.DateField(auto_now=True)),
                (
                    "bantuan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bantuan.bantuan",
                    ),
                ),
                (
                    "diverifikasi_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "masyarakat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masyarakat.masyarakat",
                    ),
                ),
            ],
        ),
    ]
