# Generated by Django 5.2.3 on 2026-03-27 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bantuan", "0001_initial"),
        ("masyarakat", "0006_alter_masyarakat_nama_alter_masyarakat_nik_and_more"),
        ("pengajuan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengajuan",
            name="bantuan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bantuan.bantuan",
            ),
        ),
        migrations.AlterField(
            model_name="pengajuan",
            name="diverifikasi_oleh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pengajuan",
            name="masyarakat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="masyarakat.masyarakat",
            ),
        ),
    ]
