# Generated by Django 5.2.3 on 2026-03-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Masyarakat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nik", models.CharField(max_length=16, unique=True)),
                ("no_kk", models.CharField(max_length=16)),
                ("nama", models.CharField(max_length=100)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[
                            ("Laki-laki", "Laki-laki"),
                            ("Perempuan", "Perempuan"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tempat_lahir", models.CharField(max_length=100)),
                ("tanggal_lahir", models.DateField()),
                ("alamat", models.TextField()),
                ("rt", models.CharField(blank=True, max_length=5, null=True)),
                ("rw", models.CharField(blank=True, max_length=5, null=True)),
                ("desa", models.CharField(blank=True, max_length=100, null=True)),
                ("kecamatan", models.CharField(blank=True, max_length=100, null=True)),
                ("kabupaten", models.CharField(blank=True, max_length=100, null=True)),
                ("provinsi", models.CharField(blank=True, max_length=100, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=13, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
