# Generated by Django 5.2.3 on 2026-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masyarakat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masyarakat",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="masyarakat",
            name="jenis_kelamin",
            field=models.CharField(
                blank=True,
                choices=[("Laki-laki", "Laki-laki"), ("Perempuan", "Perempuan")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="masyarakat",
            name="tanggal_lahir",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="masyarakat",
            name="tempat_lahir",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
