# Generated by Django 5.2.3 on 2026-03-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masyarakat", "0002_alter_masyarakat_alamat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wilayah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
