# Generated by Django 5.2.3 on 2026-03-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masyarakat", "0003_wilayah"),
    ]

    operations = [
        migrations.AddField(
            model_name="masyarakat",
            name="wilayah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="masyarakat.wilayah",
            ),
        ),
        migrations.AddField(
            model_name="wilayah",
            name="kode",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="wilayah",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
