# Generated by Django 5.2.3 on 2026-03-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masyarakat", "0005_masyarakat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masyarakat",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="masyarakat",
            name="nik",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="masyarakat",
            name="no_kk",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
