# Generated by Django 5.2.3 on 2026-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masyarakat", "0006_alter_masyarakat_nama_alter_masyarakat_nik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masyarakat",
            name="foto_ktp",
            field=models.ImageField(blank=True, null=True, upload_to="ktp/"),
        ),
    ]
