# Generated by Django 5.2.3 on 2026-03-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bantuan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("tanggal_dibuat", models.DateField(auto_now_add=True)),
                ("tanggal_diperbarui", models.DateField(auto_now=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bantuan.kategori",
                    ),
                ),
            ],
        ),
    ]
