# Generated by Django 5.2.3 on 2026-03-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bantuan", "0001_initial"),
        ("masyarakat", "0003_wilayah"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenerimaBantuan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_terima", models.DateField(auto_now_add=True)),
                ("catatan", models.TextField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "bantuan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bantuan.bantuan",
                    ),
                ),
                (
                    "masyarakat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masyarakat.masyarakat",
                    ),
                ),
            ],
        ),
    ]
